# Generated by Django 4.1.5 on 2023-03-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localghosts', '0002_remove_test_user_remove_user_user_name_test_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='calci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Request_shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='', max_length=20)),
                ('total_load', models.CharField(default='', max_length=20)),
                ('product', models.CharField(default='', max_length=20)),
                ('origin', models.CharField(default='', max_length=20)),
                ('destination', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
